### ISSUE TITLE
npm run server, error

### ISSUE THREAD

**Issue by zhangzhengde0225** [alwxkxk/iot-visualization-examples#18]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/32952620/164468328-55035f82-f1c8-4ae8-ac0e-e255a8e84a5a.png">

Hey, friend,
   I'm trying to run your example, an error occurred when `npm run server`, can you explain it for me? thank you

**Comment by zhangzhengde0225** [comment]
Complete log is as follows: 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/32952620/164469192-a3731b20-8049-41ca-a13d-294f4bb18c0f.png">

**Comment by alwxkxk** [comment]
This is an error in doc.  

Try `npm run dev`.
